[versions]
vaadin = "24.3.6"
# https://repo1.maven.org/maven2/org/slf4j/slf4j-api/
slf4j = "2.0.12"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
vaadin-boot = "com.github.mvysny.vaadin-boot:vaadin-boot:12.2"
vaadin-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin" }
karibu-testing = "com.github.mvysny.kaributesting:karibu-testing-v24:2.1.4"
karibu-dsl = "com.github.mvysny.karibudsl:karibu-dsl-v23:2.1.2"
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:1.10.2"
dynatest = "com.github.mvysny.dynatest:dynatest:0.24"

[plugins]
vaadin = { id = "com.vaadin", version.ref = "vaadin" }
